### ISSUE TITLE
[Feature]: user tutorial in console

### ISSUE THREAD

**Issue by lumyjuwon** [dogu-team/dogu#115]
### Problem
After signup, there's no guide instruction for new user. Only organization page is shown.

### Solution brainstorm

Guide to do tutorials in console like browserstack

<img width="967" alt="Screenshot 2023-07-10 at 12 36 53 PM" src="https://github.com/dogu-team/dogu/assets/16658067/afc227d2-18e0-4984-8212-193b7cb53c5f">

**Comment by Ikalli** [comment]
1. When user signup, add new organization seemlessly and redirect to organization
  - Org name: `username's organization`
2. When adding a project, user meets 2 options
  - demo project(console server delivers it)
  - user configured project

**Comment by Ikalli** [comment]
In v1.3.0, Show minimum tutorial for project,

Next version, show organization tutorial
