### ISSUE TITLE
[Feature]: Remote device job's `unit` result

### ISSUE THREAD

**Issue by Ikalli** [dogu-team/dogu#161]
### Problem

Deeper inside remote device job, user might use test frameworks like pytest, jest ...
So I'd like to display unit level result in remote device job

### Solution brainstorm

Dogu agent send above information to console

**Comment by oneofthezombies** [comment]
(Based on existing dest terms) units must be present at the top as well as at the bottom of the job to facilitate pytest, jest support, and view cc @dev-kyun
