### ISSUE TITLE
[Bug]: Dost is an untrusted developer when running on a mac

### ISSUE THREAD

**Issue by oneofthezombies** [dogu-team/dogu#19]
### Steps to reproduce

1. Download Dost from Github release
2. Run Dost

### Expected behavior

Untrusted Developer Popup Does Not Appear

### Actual behavor

Untrusted developer pop-up appears

### Version

Dost-1.0.0

**Comment by yowpark** [comment]
app trusted. download github action bulid-dost's artifact. and that's ok
