### ISSUE TITLE
[Bug]: Failure to build iOSDeviceAgent while setting self-host Agent

### ISSUE THREAD

**Issue by chachamelon** [dogu-team/dogu#284]
### Steps to reproduce

[Precondition]
1. Host connection completion status due to token
2. During iOS setup, everything except iOSDeviceAgent is completed

[step]
1. Changed DoguDev, DoguDevRunner, DoguScreen, and DoguRunner Signing Team
2. Check that the error message disappears
3. Click Build&Check in Agent

### Expected behavior

Build and check should work normally.

### Actual behavor

The build fails, and the signing team returns to Unknown Name. It feels like something is being initialized?

Video Link attached :)

https://drive.google.com/file/d/1id7yGSPdDXE7YrisDcIUKWqC8QrzbxiF/view?usp=share_link

### Version

Dogu 1.5.1, Agent 1.5.0

**Comment by yowpark** [comment]
https://github.com/dogu-team/dogu/issues/283 Similar to this issue. There was a problem with overwriting the project folder with a new one at build time.
It will be fixed and distributed soon. I'll leave a comment on this issue when the release version is decided.

**Comment by chachamelon** [comment]
Thank you for your response. Due to company policy, I can't use Slack at the moment, but I will try it out when a new version is released.

**Comment by yowpark** [comment]
@chachamelon Would you try with Dogu Agent 1.6.2 version? https://github.com/dogu-team/dogu/releases/tag/v1.6.2
It would be better to update the Dogu console to version 1.6.0.

**Comment by chachamelon** [comment]
@yowpark Thank you for the swift action. I have confirmed that the build is successful. I will proceed to close the issue :)
