### ISSUE TITLE
[Bug]: WebDriverAgent button is visible in Windows OS in the Lost Settings window

### ISSUE THREAD

**Issue by oneofthezombies** [dogu-team/dogu#29]
### Steps to reproduce

1. Turn on "Dost" and go to the settings page

### Expected behavior

1. The Web Driver Agent button should not be visible in the Windows OS

### Actual behavor

The WebDriverAgent button is visible in the Windows OS

### Version

Dost 1.0.0

**Comment by yowpark** [comment]
fixed with ios configuration guide
https://github.com/dogu-team/dogu/issues/16
