### ISSUE TITLE
[Bug]: iOS <-> Dogu Agent 상 연결 오류 시 Dogu Web Console 상태값 표기 오류

### ISSUE THREAD

**Issue by QualityAssuranceJunK** [dogu-team/dogu#314]
### Environment

Self-Hosted

### Steps to reproduce

1.  iOS <-> Dogu Agent 상 연결 후 스트리밍 동작 진행
2. 5분여 정도 스트리밍 작업 진행 시 또다른 Dog Dev 충동 메시지 나온 후 앱 스트리밍 서비스 종료
3. Dogu Web Console에서 상태 값 확인

### Expected behavior

비정상적인 앱 종료 시 Dogu Web Console에서 상태 값이 정상적으로 변경이 되어야함

### Actual behavor

Dogu Web Console에서 정상적으로 동작한다는 상태 값으로 표시 및 스트리밍을 사용할 수 있도록 되어있음

### Version

Dogu : 1.7
Dogu Agent : 1.7

**Comment by Ikalli** [comment]
안녕하세요 @QualityAssuranceJunK! 좋은 이슈 감사합니다👍

해당 이슈는 스트리밍이 가능한지 상태값을 알 수 없어 생기는 현상인 것 같습니다. 이는 #297 이슈를 통해 해결할 수 있어 보입니다. iOS에서 스트리밍이 불안정한 현상은 Dogu의 코드 상 문제가 있거나, Apple쪽의 문제일 수 있어서 시간을 들여 봐야할 것 같습니다

**Comment by Ikalli** [comment]
Hi @QualityAssuranceJunK!

This issue has been resolved as a new feature in v1.11.2 release!
Please check release note: https://github.com/dogu-team/dogu/releases/tag/v1.11.2

Thanks for reporting good issue!👍
