### ISSUE TITLE
[Bug]: Even if the console server goes down, the host connection is still connected.

### ISSUE THREAD

**Issue by yowpark** [dogu-team/dogu#324]
### Environment

Development (for Dogu developers)

### Steps to reproduce

Connect Dogu-Agent to console,
Shutdown console server

### Expected behavior

Dogu-Agent's status should be disconnected

### Actual behavor

Dogu-Agent is still Conencted.

### Version

1.7.0

**Comment by oneofthezombies** [comment]
https://github.com/dogu-team/dogu/commit/1b113ed59bc340fd836059f9c3c06e2d9317e3ca
https://github.com/dogu-team/dogu/commit/3c05c4e8d6933035d88579a272497efe2aef28a8
