### ISSUE TITLE
[Bug]: Routine step log missing

### ISSUE THREAD

**Issue by yowpark** [dogu-team/dogu#325]
### Environment

Development (for Dogu developers)

### Steps to reproduce

Run some routine

### Expected behavior

all routine step logs should be printed

### Actual behavor

some routine step logs are missing

### Version

1.7.0

**Comment by oneofthezombies** [comment]
see 
c88207f83eb73d3a51027c68a5514ce125060024
f2aca6afc924c613a24191d61bc3a72761bc3650
