### ISSUE TITLE
[Refactor]: Rename dost

### ISSUE THREAD

**Issue by lumyjuwon** [dogu-team/dogu#41]
### Problem

We need to rename dost not to confuse

### Update

Dost -> Dogu Agent

**Comment by lumyjuwon** [comment]
* Dost App
* Landing
* Console
* Docs

**Comment by yowpark** [comment]
ci app name changed
https://github.com/dogu-team/dogu/commit/4c127888c30b365b59a654a58dd74a61597a94d7

**Comment by Ikalli** [comment]
UI text changed
- Dogu agent
- Console

**Comment by lumyjuwon** [comment]
Docs changed
