### ISSUE TITLE
[Feature]: Integrate with github, gitlab

### ISSUE THREAD

**Issue by lumyjuwon** [dogu-team/dogu#53]
### Problem

We need feature to integrate repository of project with github or gitlab

### Solution brainstorm

1. Develop UI for integrating with github or gitlab
2. Use SDK of github or gitlab for getting meta of repository

**Comment by Ikalli** [comment]
Plan:

1. [Console] Create project and move to git integrate page
2. [Console] Enter git token and `config` path(ex. `.` or `/`)
3. [API Server] Encrypt and save git token, save config path to DB

@dev-kyun
